### ISSUE TITLE
Creating Frame issue

### ISSUE THREAD

**Issue by JacobusS** [Kylsha/map_tile_loader#1]
Hi, when I click on the Add Frame button I get the following error:
argument 2 has unexpected type 'bool'

Traceback (most recent call last):
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\map_tile_loader\map_tile_loader_dialog.py", line 403, in draw_rect
    self.draw_tool = rband(iface.mapCanvas(), self)
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\map_tile_loader\map_tile_loader_dialog.py", line 207, in __init__
    self.rubberBand = QgsRubberBand(self.canvas, True)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

**Comment by pavelpereverzev** [comment]
Fixed

**Comment by JacobusS** [comment]
Fantastic thanks

**Comment by JacobusS** [comment]
Fantastic. Thanks for the help. Great plug in by the way
