### ISSUE TITLE
Error installing the extension

### ISSUE THREAD

**Issue by barcia** [Kylsha/map_tile_loader#4]
Hi, I’m having trouble installing the extension.
I’m getting an error related to the classFactory() method.

Python: 3.9.5
QGIS: 3.40.1

<img width="1022" alt="Captura de pantalla 2024-12-30 a las 23 10 40" src="https://github.com/user-attachments/assets/b829a02f-e427-4f6f-9c6f-044fee87f5f0" />

**Comment by pavelpereverzev** [comment]
@barcia hello! Looks like some part of code has to be changed for MacOS. Unfortunately I have no a device with MacOS right now. I can reach one apparently in the middle of January 2025, so now the solution would be using Windows version of QGIS and this plugin as well.

**Comment by eithanwes** [comment]
@pavelpereverzev 
Hi!
I'm a PC user and I get the same error.


```
Couldn't load plugin 'map_tile_loader' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS34~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\map_tile_loader\__init__.py", line 36, in classFactory
    return TileLoader(iface)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\map_tile_loader\map_tile_loader.py", line 51, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'QVariant' object is not subscriptable


Python version: 3.12.10 (main, Apr  9 2025, 08:14:47) [MSC v.1943 64 bit (AMD64)] 
QGIS version: 3.40.6-Bratislava Bratislava, 5d7f6a3e26 

Python Path:
C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\last_mile_toolbox
C:/PROGRA~1/QGIS34~1.6/apps/qgis-ltr/./python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS34~1.6/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS34~1.6\apps\grass\grass84\etc\python
C:\Users\user\Documents
C:\Program Files\QGIS 3.40.6\bin\python312.zip
C:\PROGRA~1\QGIS34~1.6\apps\Python312\DLLs
C:\PROGRA~1\QGIS34~1.6\apps\Python312\Lib
C:\Program Files\QGIS 3.40.6\bin
C:\Users\user\AppData\Roaming\Python\Python312\site-packages
C:\PROGRA~1\QGIS34~1.6\apps\Python312
C:\PROGRA~1\QGIS34~1.6\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS34~1.6\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS34~1.6\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS34~1.6\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by pavelpereverzev** [comment]
@barcia @eithan-lastmile Hello there!
I looked carefully at the error text. Looks like there is an error related to QGIS locale settings, i.e., it can't reach the language used in QGIS.

If you type this in QGIS console you may see that it's NULL or something like that:

```
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
print(QSettings().value('locale/userLocale'))
```

As a workaround try changing languages in QGIS: go to Settings - Options - General - check "Override system locale" and select desired languages in both interface and translations (is exists). Then re-open QGIS and try launhing map_tile_loader again.
